### ISSUE TITLE
connect-outlook failed

### ISSUE THREAD

**Issue by jm0477** [iricigor/OutlookConnector#1]
when i run the connect-outlook cmdlet, it fails.
Could you describe what is the correct way to connected to my outlook?

Can not obtain Outlook COM object. Try running Start-Outlook and then repeat command.
At C:\Program Files\WindowsPowerShell\Modules\outlookconnector\0.92.1\Connect-Outlook.ps1:59 char:5
-     throw ('Can not obtain Outlook COM object. Try running Start-Outl ...
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : OperationStopped: (Can not obtain ...epeat command. :String) [], RuntimeException
  - FullyQualifiedErrorId : Can not obtain Outlook COM object. Try running Start-Outlook and then repeat command.

**Comment by jm0477** [comment]
After closed my outlook GUI, it worked. 
Any clue how to list the calendar event?

**Comment by kort3x** [comment]
So, this a thing? Not working while outlook is opened? bummer

**Comment by iricigor** [comment]
Nope, that is not the thing. It works when Outlook is opened.
